export default () => ({
  exam: {
    hashId: '',
    payementTypeId: 0,
    title: '',
    image: 'https://storage.tracnghiem.vn/tracnghiem-dev/exam-avatar.png',
    description: '',
    nonExamTime: true,
    examTime: 0,
    maximumTest: 0,
    numberQuestionsTest: 0,
    suffleQuestions: true,
    suffleAnswers: true,
    checkAnswersWhileTest: true,
    checkAnswersAfterTest: true,
    allowChangeSettings: true,
    statusId: 0,
    levelId: 0,
    seoTitle: '',
    seoDescription: '',
    categories: [],
    tags: [],
  },
})
