FROM node:lts  as frontend-build
ENV apiURI https://dev-api.tracnghiem.vn
ENV NODE_ENV development
WORKDIR /src

ADD yarn.lock package.json package-lock.json ./
RUN yarn install \
  --prefer-offline \
  --frozen-lockfile \
  --non-interactive \
  --production=false
ADD . .
RUN rm -rf node_modules && \
  NODE_ENV=development yarn install \
  --prefer-offline \
  --pure-lockfile \
  --non-interactive \
  --production=true



FROM node:15.11.0-alpine3.12
EXPOSE 3000
WORKDIR /app

COPY --from=frontend-build /src . 
CMD [ "yarn", "start" ]